// GENERATED by scripts/apply-app-identity.mjs — do not edit.
// Change the name in app.config.json and run `npm run app:name`.

/// The product's name, as shown inside the app.
///
/// Separate from the store listing title, which must be globally unique and is
/// therefore often longer. This is what a student reads on the sign-in screen.
class AppInfo {
  const AppInfo._();

  static const String name = "MealAdda";
  static const String supportEmail = "support@mealadda.in";

  /// The permanent public origin: the API base URL and the legal pages.
  static const String website = "https://www.mealadda.in";

  /// Shown under the account menu, and quoted in support conversations.
  static const String version = "1.0.0";

  /// The store's build number. Compared against the server's minimum on launch.
  static const int build = 1;
}
