// GENERATED by scripts/apply-app-identity.mjs — do not edit.
// Change the name in app.config.json and run `npm run app:name`.

/// The product's name, as shown inside the app.
///
/// Separate from the store listing title, which must be globally unique and is
/// therefore often longer. This is what a student reads on the sign-in screen.
class AppInfo {
  const AppInfo._();

  static const String name = "MessMate";
  static const String supportEmail = "support@messmate.app";
}
